% @Author: Jan Brejcha <ibrejcha>
% @Date:   2017-02-13T16:53:18+01:00
% @Email:  ibrejcha@fit.vutbr.cz, brejchaja@gmail.com
% @Project: Locate
% @Last modified by:   ibrejcha
% @Last modified time: 2017-02-14T11:01:12+01:00


% trains geoPose3K + wallis small with heading 360 deg and camera tilt 80 
% deg


dbTrain= dbGESS_ws_360_80('train'); dbVal= dbGESS_ws_360_80('val');

trainWeakly(dbTrain, dbVal, ...
    'netID', 'vd16', 'layerName', 'conv5_3', ...
    'method', 'vlad_preL2_intra', 'backPropToLayer', 'conv5_3', ...
    'margin', 0.1, ...
    'batchSize', 10, 'learningRate', 0.001, 'lrDownFreq', 3, 'momentum', 0.9, 'weightDecay', 0.1, 'compFeatsFrequency', 5, ...
    'nNegChoice', 30, 'nNegCap', 10, 'nNegCache', 10, ...
    'nEpoch', 10, ...
    'epochTestFrequency', 1, 'test0', true, ...
    'nTestSample', inf, 'nTestRankSample', 40, ...
    'saveFrequency', 15, 'doDraw', true, ...
    'useGPU', true, 'numThreads', 12, ...
    'computeBatchSize', 80, ...
    'sessionID', 'd5ad', ...
    'startEpoch', 2, ...
    'info', 'tiny test');

